// <auto-generated />
using System;
using MatchFlix;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchFlix.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MatchFlix.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id_Avaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Avaliacao"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Sessao_Filme")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<bool>("like")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id_Avaliacao");

                    b.HasIndex("Id_Sessao_Filme");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("MatchFlix.Models.Filme", b =>
                {
                    b.Property<int>("Id_Filme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Filme"));

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("int");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<string>("Poster_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Filme");

                    b.ToTable("Filme");
                });

            modelBuilder.Entity("MatchFlix.Models.FilmeGenero", b =>
                {
                    b.Property<int>("Id_Filme")
                        .HasColumnType("int");

                    b.Property<int>("Id_Genero")
                        .HasColumnType("int");

                    b.HasKey("Id_Filme", "Id_Genero");

                    b.HasIndex("Id_Genero");

                    b.ToTable("Filme_Genero");
                });

            modelBuilder.Entity("MatchFlix.Models.Genero", b =>
                {
                    b.Property<int>("Id_Genero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Genero"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Genero");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("MatchFlix.Models.GrupoSessao", b =>
                {
                    b.Property<int>("Id_Grupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Grupo"));

                    b.Property<string>("CodigoConvite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataCriaçao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Id_Usuario_Criador")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Grupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Grupo");

                    b.HasIndex("Id_Usuario_Criador");

                    b.ToTable("Grupo_Sessao");
                });

            modelBuilder.Entity("MatchFlix.Models.Match", b =>
                {
                    b.Property<int>("id_match")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_match"));

                    b.Property<DateTime>("DataMacth")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Filme")
                        .HasColumnType("int");

                    b.Property<int>("Id_Sessao")
                        .HasColumnType("int");

                    b.Property<int>("Total_Likes")
                        .HasColumnType("int");

                    b.HasKey("id_match");

                    b.HasIndex("Id_Filme");

                    b.HasIndex("Id_Sessao");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("MatchFlix.Models.MembroGrupo", b =>
                {
                    b.Property<int>("Id_Membro_Grupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Membro_Grupo"));

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Grupo")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Membro_Grupo");

                    b.HasIndex("Id_Grupo");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Membro_Grupo");
                });

            modelBuilder.Entity("MatchFlix.Models.Sessao", b =>
                {
                    b.Property<int>("Id_Sessao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Sessao"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Grupo")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Sessao");

                    b.HasIndex("Id_Grupo");

                    b.ToTable("Sessao");
                });

            modelBuilder.Entity("MatchFlix.Models.SessaoFilme", b =>
                {
                    b.Property<int>("Id_Sessao_Filme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Sessao_Filme"));

                    b.Property<int>("Id_Filme")
                        .HasColumnType("int");

                    b.Property<int>("Id_Sessao")
                        .HasColumnType("int");

                    b.HasKey("Id_Sessao_Filme");

                    b.HasIndex("Id_Filme");

                    b.HasIndex("Id_Sessao");

                    b.ToTable("Sessao_Filme");
                });

            modelBuilder.Entity("MatchFlix.Models.Usuarios", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MatchFlix.Models.Avaliacao", b =>
                {
                    b.HasOne("MatchFlix.Models.SessaoFilme", "SessaoFilme")
                        .WithMany()
                        .HasForeignKey("Id_Sessao_Filme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchFlix.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessaoFilme");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MatchFlix.Models.FilmeGenero", b =>
                {
                    b.HasOne("MatchFlix.Models.Filme", "Filme")
                        .WithMany()
                        .HasForeignKey("Id_Filme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchFlix.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("Id_Genero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filme");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("MatchFlix.Models.GrupoSessao", b =>
                {
                    b.HasOne("MatchFlix.Models.Usuarios", "UsuariosCriador")
                        .WithMany()
                        .HasForeignKey("Id_Usuario_Criador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuariosCriador");
                });

            modelBuilder.Entity("MatchFlix.Models.Match", b =>
                {
                    b.HasOne("MatchFlix.Models.Filme", "Filme")
                        .WithMany()
                        .HasForeignKey("Id_Filme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchFlix.Models.Sessao", "Sessao")
                        .WithMany()
                        .HasForeignKey("Id_Sessao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filme");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("MatchFlix.Models.MembroGrupo", b =>
                {
                    b.HasOne("MatchFlix.Models.GrupoSessao", "GrupoSessao")
                        .WithMany()
                        .HasForeignKey("Id_Grupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchFlix.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoSessao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MatchFlix.Models.Sessao", b =>
                {
                    b.HasOne("MatchFlix.Models.GrupoSessao", "GrupoSessao")
                        .WithMany()
                        .HasForeignKey("Id_Grupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoSessao");
                });

            modelBuilder.Entity("MatchFlix.Models.SessaoFilme", b =>
                {
                    b.HasOne("MatchFlix.Models.Filme", "Filme")
                        .WithMany()
                        .HasForeignKey("Id_Filme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchFlix.Models.Sessao", "Sessao")
                        .WithMany()
                        .HasForeignKey("Id_Sessao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filme");

                    b.Navigation("Sessao");
                });
#pragma warning restore 612, 618
        }
    }
}
